export const MAPLIST = [
  { value: "SailAway", label: "SailAway" },
  { value: "Boreal%20Falls", label: "Boreal Falls" },
  { value: "Thermal%20Shock", label: "Thermal Shock" },
  { value: "Seths%20Ravine", label: "Seths Ravine" },
  { value: "Sphagnum%20Bog", label: "Sphagnum Bog" },
  { value: "Talus", label: "Talus" },
  { value: "Tropical%20Assault", label: "Tropical Assault" },
  { value: "Sertagatta", label: "Sertagatta" },
  { value: "Crescent%20Bay", label: "Crescent Bay" },
  { value: "Folsom%20Dam", label: "Folsom Dam" },
  { value: "Neurope", label: "Neurope" },
  { value: "Archsimkats%20Valley", label: "Archsimkats Valley" },
  { value: "Erebos%20Lakes", label: "Erebos Lakes" },
  { value: "Red%20River", label: "Red River" },
  { value: "Mithril%20Mountain", label: "Mithril Mountain" },
  { value: "Rosetta", label: "Rosetta" },
  { value: "Knockout", label: "Knockout" },
  { value: "Raptor%20Crater", label: "Raptor Crater" },
  { value: "Heartbreak%20Hill", label: "Heartbreak Hill" },
  { value: "Glacier%20Pass", label: "Glacier Pass" },
  { value: "Hades%20Ponds", label: "Hades Ponds" },
  { value: "Otago", label: "Otago" },
  { value: "Into%20Battle%20Redux", label: "Into Battle Redux" },
  { value: "Iron%20Isle", label: "Iron Isle" },
  { value: "The%20Desert%20Triad", label: "The Desert Triad" },
  { value: "Hellas%20Basin", label: "Hellas Basin" },
  { value: "Gasbag%20Grabens", label: "Gasbag Grabens" },
  { value: "Argent%20Strata", label: "Argent Strata" },
  { value: "Baryon%20Tar%20Lake", label: "Baryon Tar Lake" },
  { value: "Eight%20Horses", label: "Eight Horses" },
  { value: "Swirly%20Rock", label: "Swirly Rock" },
  { value: "Pillar%20of%20Doom", label: "Pillar of Doom" },
  { value: "Red%20Rock%20Desert", label: "Red Rock Desert" },
  { value: "Crater%20Islands", label: "Crater Islands" },
  { value: "Canis%20River", label: "Canis River" },
  { value: "Eclipsed", label: "Eclipsed" },
  { value: "Altored%20Divide", label: "Altored Divide" },
  { value: "Sinkhole%20Network", label: "Sinkhole Network" },
  { value: "Delta%20Siege%20Dry", label: "Delta Siege Dry" },
  { value: "Zed", label: "Zed" },
  { value: "Odderon%20Strandflats", label: "Odderon Strandflats" },
  { value: "Altair%20Crossing", label: "Altair Crossing" },
  { value: "Salt%20Reef", label: "Salt Reef" },
  { value: "Geyser%20Plains", label: "Geyser Plains" },
  { value: "Tangerine", label: "Tangerine" },
  { value: "Aethermoor%20Creek", label: "Aethermoor Creek" },
  { value: "Isidis%20crack", label: "Isidis crack" },
  { value: "Ravaged", label: "Ravaged" },
  { value: "Sulphur%20Springs", label: "Sulphur Springs" },
  { value: "Failed%20Negotiations", label: "Failed Negotiations" },
  { value: "Melting%20Glacier", label: "Melting Glacier" },
  { value: "Colorado", label: "Colorado" },
  { value: "Coast%20To%20Coast", label: "Coast To Coast" },
  { value: "The%20Rock", label: "The Rock" },
  { value: "Houses%20of%20Tripolis", label: "Houses of Tripolis" },
  { value: "Eternal%20Consequences", label: "Eternal Consequences" },
  { value: "Requiem%20Outpost", label: "Requiem Outpost" },
  { value: "Kings%20Assault", label: "Kings Assault" },
  { value: "Wanderlust", label: "Wanderlust" },
  { value: "Trefoil", label: "Trefoil" },
  { value: "Cirolata", label: "Cirolata" },
  { value: "Serene%20Caldera", label: "Serene Caldera" },
  { value: "Darkside", label: "Darkside" },
  { value: "Ring%20Atoll", label: "Ring Atoll" },
  { value: "Death%20Valley", label: "Death Valley" },
  { value: "Pentos", label: "Pentos" },
  { value: "Frozen%20Ford", label: "Frozen Ford" },
  { value: "Seven%20Rivers", label: "Seven Rivers" },
  { value: "BarR", label: "BarR" },
  { value: "Quicksilver", label: "Quicksilver" },
  { value: "Devil's%20Postpiles", label: "Devil's Postpiles" },
  { value: "Lavender%20Bender", label: "Lavender Bender" },
  { value: "All%20That%20Glitters%20Extended", label: "All That Glitters Extended" },
  { value: "The%20Barrier%20Reef", label: "The Barrier Reef" },
  { value: "Callisto", label: "Callisto" },
  { value: "Desolation", label: "Desolation" },
  { value: "Onyx%20Cauldron", label: "Onyx Cauldron" },
  { value: "Charlie%20In%20The%20Hills", label: "Charlie In The Hills" },
  { value: "Adamantium%20Factory", label: "Adamantium Factory" },
  { value: "Tumult", label: "Tumult" },
  { value: "Shore%20to%20Shore", label: "Shore to Shore" },
  { value: "Asteroid%20Mines", label: "Asteroid Mines" },
  { value: "Center%20Command", label: "Center Command" },
  { value: "Tau", label: "Tau" },
  { value: "World%20In%20Flames", label: "World In Flames" },
  { value: "The%20Rock%20Jungle", label: "The Rock Jungle" },
  { value: "Forge", label: "Forge" },
  { value: "Ice%20Scream", label: "Ice Scream" },
  { value: "Special%20Creek", label: "Special Creek" },
  { value: "Crubick%20Plains", label: "Crubick Plains" },
  { value: "Tabula", label: "Tabula" },
  { value: "TMA20X", label: "TMA20X" },
  { value: "Gods%20of%20War", label: "Gods of War" },
  { value: "Red%20River%20Estuary", label: "Red River Estuary" },
  { value: "Hotstepper%205", label: "Hotstepper 5" },
  { value: "Hide%20and%20Seek", label: "Hide and Seek" },
  { value: "Rifted", label: "Rifted" },
  { value: "Throne", label: "Throne" },
  { value: "Tetrad", label: "Tetrad" },
  { value: "Sky%20Isle", label: "Sky Isle" },
  { value: "Painted%20Desert", label: "Painted Desert" },
  { value: "Emain%20Macha", label: "Emain Macha" },
  { value: "Kolmogorov", label: "Kolmogorov" },
  { value: "Boulder%20Beach", label: "Boulder Beach" },
  { value: "Claymore", label: "Claymore" },
  { value: "DSD%208%20Way", label: "DSD 8 Way" },
  { value: "Ancient%20Vault", label: "Ancient Vault" },
  { value: "Mariposa%20Island", label: "Mariposa Island" },
  { value: "Scylla%20and%20Charybdis", label: "Scylla and Charybdis" },
  { value: "Krakatoa", label: "Krakatoa" },
  { value: "Twin%20Lakes%20Park", label: "Twin Lakes Park" },
  { value: "Supreme%20Crossing%202", label: "Supreme Crossing 2" },
  { value: "Centerrock", label: "Centerrock" },
  { value: "Red%20Triangle", label: "Red Triangle" },
  { value: "Greenhaven", label: "Greenhaven" },
  { value: "Taldarim", label: "Taldarim" },
  { value: "Avalanche", label: "Avalanche" },
  { value: "Red%20Comet", label: "Red Comet" },
  { value: "Hyperion%20Shale", label: "Hyperion Shale" },
  { value: "Rustcrown%20Canyon", label: "Rustcrown Canyon" },
  { value: "Prismatic%20Anomaly", label: "Prismatic Anomaly" },
  { value: "Ditched", label: "Ditched" },
  { value: "Incandescence", label: "Incandescence" },
  { value: "Pawn%20Retreat", label: "Pawn Retreat" },
  { value: "Pinch%20Point", label: "Pinch Point" },
  { value: "Mediterraneum", label: "Mediterraneum" },
  { value: "DWorld", label: "DWorld" },
  { value: "Riverrun", label: "Riverrun" },
  { value: "Aurelia", label: "Aurelia" },
  { value: "Mescaline", label: "Mescaline" },
  { value: "LV412", label: "LV412" },
  { value: "Glacial%20Gap", label: "Glacial Gap" },
  { value: "Flooded%20Valley", label: "Flooded Valley" },
  { value: "Deeploria%20Fields", label: "Deeploria Fields" },
  { value: "Sertaleina", label: "Sertaleina" },
  { value: "Pools%20of%20Ilys", label: "Pools of Ilys" },
  { value: "Full%20Metal%20Plate", label: "Full Metal Plate" },
  { value: "SpeedMetal", label: "SpeedMetal" },
  { value: "Esker%20Creek", label: "Esker Creek" },
  { value: "Ghenna%20Rising", label: "Ghenna Rising" },
  { value: "Cloud9", label: "Cloud9" },
  { value: "Plains%20and%20Passes", label: "Plains and Passes" },
  { value: "Koom%20Valley", label: "Koom Valley" },
  { value: "Jade%20Empress", label: "Jade Empress" },
  { value: "Valles%20Marineris", label: "Valles Marineris" },
  { value: "Project%20SD-129", label: "Project SD-129" },
  { value: "Supreme%20Isthmus", label: "Supreme Isthmus" },
  { value: "Silveridge", label: "Silveridge" },
  { value: "Azurite%20Shores", label: "Azurite Shores" },
  { value: "Titan", label: "Titan" },
  { value: "Paradise%20Lost", label: "Paradise Lost" },
  { value: "Fallendell", label: "Fallendell" },
  { value: "All%20That%20Glitters", label: "All That Glitters" },
  { value: "Industrial%20Revolution", label: "Industrial Revolution" },
  { value: "Silent%20Sea", label: "Silent Sea" },
  { value: "Entrenched%20Plains", label: "Entrenched Plains" },
  { value: "Eye%20Of%20Horus", label: "Eye Of Horus" },
  { value: "To%20Kill%20The%20Middle", label: "To Kill The Middle" },
  { value: "Crystallized%20Plains", label: "Crystallized Plains" },
  { value: "Bismuth%20Valley", label: "Bismuth Valley" },
  { value: "Sunderance", label: "Sunderance" },
  { value: "Comet%20Catcher", label: "Comet Catcher" },
  { value: "The%20Halite%20Maze", label: "The Halite Maze" },
  { value: "Ascendancy", label: "Ascendancy" },
  { value: "Great%20Divide", label: "Great Divide" },
  { value: "White%20Fire", label: "White Fire" },
  { value: "Gecko%20Isle", label: "Gecko Isle" },
  { value: "Small%20Supreme%20Battlefield", label: "Small Supreme Battlefield" },
  { value: "Angel%20Crossing", label: "Angel Crossing" },
  { value: "Digsite", label: "Digsite" },
  { value: "Special%20Reef", label: "Special Reef" },
  { value: "Hera%20Planum", label: "Hera Planum" },
  { value: "Flats%20and%20Forests", label: "Flats and Forests" },
  { value: "Tempest", label: "Tempest" },
  { value: "High%20Noon", label: "High Noon" },
  { value: "Oort%20Cloud", label: "Oort Cloud" },
  { value: "Tundra", label: "Tundra" },
  { value: "Sector%20318C", label: "Sector 318C" },
  { value: "Blindside", label: "Blindside" },
  { value: "Why%20did%20I%20let%20PtaQ%20talk%20me%20into%20this", label: "Why did I let PtaQ talk me into this" },
  { value: "Faster%20Than%20Light", label: "Faster Than Light" },
  { value: "Coastlines%20Dry", label: "Coastlines Dry" },
  { value: "Carrot%20Mountains", label: "Carrot Mountains" },
  { value: "All%20That%20Smolders", label: "All That Smolders" },
  { value: "Moonshine%20Run", label: "Moonshine Run" },
  { value: "Supreme%20Crossing", label: "Supreme Crossing" },
  { value: "Titan%20Duel", label: "Titan Duel" },
  { value: "Tundra%20Continents", label: "Tundra Continents" },
  { value: "Vittra", label: "Vittra" },
  { value: "Salmiakki", label: "Salmiakki" },
  { value: "Crimson%20Bay", label: "Crimson Bay" },
  { value: "Hooked", label: "Hooked" },
  { value: "Proving%20Grounds", label: "Proving Grounds" },
  { value: "All%20That%20Simmers", label: "All That Simmers" },
  { value: "MoonQ20XR2", label: "MoonQ20XR2" },
  { value: "Shallow%20Straits", label: "Shallow Straits" },
  { value: "Stronghold", label: "Stronghold" },
  { value: "Sand%20Crowns", label: "Sand Crowns" },
  { value: "Factions%20and%20Factious", label: "Factions and Factious" },
  { value: "The%20Tartar%20Steppe", label: "The Tartar Steppe" },
  { value: "The%20Cold%20Place", label: "The Cold Place" },
  { value: "Theta%20Crystals", label: "Theta Crystals" },
  { value: "Point%20of%20No%20Return", label: "Point of No Return" },
  { value: "Hotlips", label: "Hotlips" },
  { value: "Starwatcher", label: "Starwatcher" },
  { value: "Evad%20River%20Confluence", label: "Evad River Confluence" },
  { value: "Cape%20Violet", label: "Cape Violet" },
  { value: "Greenest%20Fields", label: "Greenest Fields" },
  { value: "Feast%20of%20Hades", label: "Feast of Hades" },
  { value: "Black%20Star", label: "Black Star" },
  { value: "Special%20Hotstepper", label: "Special Hotstepper" },
  { value: "ReRaghnarok", label: "ReRaghnarok" },
  { value: "Riverdale", label: "Riverdale" },
  { value: "Nine%20Metal%20Islands", label: "Nine Metal Islands" },
  { value: "Ancient%20Bastion", label: "Ancient Bastion" },
  { value: "Timna%20Island", label: "Timna Island" },
  { value: "Copper%20Hill", label: "Copper Hill" },
  { value: "Cells", label: "Cells" },
  { value: "Lake%20Carne", label: "Lake Carne" },
  { value: "Downs%20of%20Destruction", label: "Downs of Destruction" },
  { value: "Omega%20Valley", label: "Omega Valley" },
  { value: "Plethora%20of%20Ponds", label: "Plethora of Ponds" },
  { value: "Pinewood%20Derby", label: "Pinewood Derby" },
  { value: "Nuclear%20Winter", label: "Nuclear Winter" },
  { value: "Acidic%20Quarry", label: "Acidic Quarry" }
]