import {
  LocateFixed,
  StepForward,
  FoldHorizontal,
  Crosshair,
  Plane,
  Bot,
  Wind,
  Mouse,
  TrendingUp,
  Swords,
  Crown,
  Zap,
  Rocket,
  PocketKnife,
  ArrowRightLeft,
  Flag,
  BowArrow,
  Bomb,
  Scale,
  SquareArrowUp,
  Popcorn,
  Users,
} from "lucide-react";

export const MILESTONE_CATEGORIES = [
  { key: "lobby", label: "Lobby Settings" },
  { key: "timings", label: "Timings" },
  { key: "outcomes", label: "Outcomes" },
  { key: "gameplay", label: "Gameplay" },
  { key: "social", label: "Social" },
];

export const MILESTONES = [
  {
    key: "ecoBoost",
    label: "Eco Boost",
    icon: Rocket,
    color: "--color-upset",
    weight: 0,
    category: "lobby",
    description:
      "Metal or energy boosted in game options, worth no points.",
  },
  {
    key: "extraUnits",
    label: "Extra Units",
    icon: Bot,
    color: "--color-upset",
    weight: 0,
    category: "lobby",
    description:
      "Experimental or Scav units enabled in game options, worth no points.",
  },
  {
    key: "modded",
    label: "Modded",
    icon: Bot,
    color: "--color-upset",
    weight: 0,
    category: "lobby",
    description:
      "Mods are installed, worth no points.",
  },
  {
    key: "upset",
    label: "Imbalanced",
    icon: Scale,
    color: "--color-upset",
    weight: 0,
    category: "lobby",
    description:
      "Noticable skill gap between teams regardless of outcome, worth no points.",
  },
  {
    key: "legionMatch",
    label: "Legion Match",
    icon: Bot,
    color: "--color-eco",
    weight: 0,
    category: "lobby",
    description: "Legion faction detected in this game, worth no points.",
  },
  {
    key: "pve",
    label: "PvE",
    icon: Users,
    color: "--color-close",
    weight: 0,
    category: "lobby",
    description: "Co-op vs AI match — all players on the same team.",
  },
  {
    key: "earlyBombing",
    label: "Early Bombing",
    icon: Plane,
    color: "--color-combat",
    weight: 2,
    category: "timings",
    description: "At least 5 bomber built before 10 minutes.",
  },
  {
    key: "quickForfeit",
    label: "Quick Forfeit",
    icon: Flag,
    color: "--color-upset",
    weight: -3,
    category: "timings",
    description:
      "Premature forfeits reduce spectator score, weighted more for large teams.",
  },
  {
    key: "gantryRush",
    label: "T3 Rush",
    icon: SquareArrowUp,
    color: "--color-combat",
    weight: 1,
    category: "timings",
    description:
      "T3 built relatively fast, scaled with wind speed and players (e.g., 12 mins on 15 wind 16 players).",
  },
  {
    key: "afusRush",
    label: "AFUS Rush",
    icon: Zap,
    color: "--color-eco",
    weight: 1,
    category: "timings",
    description:
      "AFUS built relatively fast, scaled with wind speed and players (e.g., 12 mins on 15 wind 16 players).",
  },
  {
    key: "nukeRush",
    label: "Nuke Rush",
    icon: Bomb,
    color: "--color-combat",
    weight: 2,
    category: "timings",
    description:
      "Nuke built relatively fast, scaled with wind speed and players (e.g., 12 mins on 15 wind 16 players).",
  },
  {
    key: "nailBiter",
    label: "Last Commander",
    icon: LocateFixed,
    color: "--color-close",
    weight: 3,
    category: "outcomes",
    description: "One commander left on winning team.",
  },
  {
    key: "windyDay",
    label: "Windy Day",
    icon: Wind,
    color: "--color-close",
    weight: 0,
    category: "outcomes",
    description: "Wind speed higher than average for the map, worth no points.",
  },
  {
    key: "stomp",
    label: "Stomp",
    icon: Crown,
    color: "--color-upset",
    weight: -2,
    category: "outcomes",
    description: "Heavily one-sided, reduces spectator score.",
  },
  {
    key: "bigBattle",
    label: "Big Battle",
    icon: Swords,
    color: "--color-combat",
    weight: 2,
    category: "gameplay",
    description: "Sharp simulteous declines in army value for both teams.",
  },
  {
    key: "comeback",
    label: "Comeback",
    icon: TrendingUp,
    color: "--color-eco",
    weight: 3,
    category: "gameplay",
    description: "Winning team once 50% behind in army value.",
  },
  {
    key: "backAndForth",
    label: "Back and Forth",
    icon: ArrowRightLeft,
    color: "--color-eco",
    weight: 2,
    category: "gameplay",
    description: "Constant momentum shifts throught the battle.",
  },
  {
    key: "guerillaFighters",
    label: "Guerilla Fighters",
    icon: BowArrow,
    color: "--color-combat",
    weight: 3,
    category: "gameplay",
    description: "High average damage per metal spent. Combat efficient.",
  },
  {
    key: "carpalTunnel",
    label: "Carpal Tunnel",
    icon: Mouse,
    color: "--color-eco",
    weight: 2,
    category: "gameplay",
    description: "High average player APM throughout the game.",
  },
  {
    key: "spaceRace",
    label: "Close Eco",
    icon: Rocket,
    color: "--color-close",
    weight: 2,
    category: "gameplay",
    description: "Close eco between teams throughout the match.",
  },
  {
    key: "techSpread",
    label: "Tech Spread",
    icon: PocketKnife,
    color: "--color-close",
    weight: 4,
    category: "gameplay",
    description:
      "Unit type diversity (bots, veh, air, sea, hov, amphib), weighted less for large games. Some units (commandos, bedbugs, spy bots) worth more.",
  },
  {
    key: "goliathDuel",
    label: "Goliath Duel",
    icon: FoldHorizontal,
    color: "--color-combat",
    weight: 5,
    category: "gameplay",
    description: "Both sides build experimental gantry built in a duel.",
  },
  {
    key: "commanderAttack",
    label: "Commander Attack",
    icon: StepForward,
    color: "--color-combat",
    weight: 3,
    category: "gameplay",
    description: "One team's commander moves into enemy start location.",
  },
  {
    key: "orbitalCannons",
    label: "Big Guns",
    icon: Crosshair,
    color: "--color-combat",
    weight: 1,
    category: "gameplay",
    description: "Ragnarok/Calamity/Starfall is built",
  },
  {
    key: "peanutGallery",
    label: "Peanut Gallery",
    icon: Popcorn,
    color: "--color-upset",
    weight: 0,
    category: "social",
    description:
      "At least 10 spectators. Generally more yapping, worth no points.",
  },
];
